[api-base]
listenPort = 8082
staticPath = "./static"


[database]
host = "127.0.0.1"
port = 3307
user = "root"
password = "200455"
dbname = "blog"

[jwt]
secret = "your-super-secret-key-change-this-in-production"
expiration = 86400  # 24小时，单位：秒

