basePath: /api
definitions:
  article.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  models.Article:
    properties:
      content:
        type: string
      cover:
        type: string
      created_at:
        type: string
      id:
        type: integer
      on_show:
        type: boolean
      status:
        type: integer
      summary:
        type: string
      tags:
        items:
          type: string
        type: array
      title:
        type: string
      updated_at:
        type: string
      views:
        type: integer
    required:
    - title
    type: object
  models.ArticleListResponse:
    properties:
      articles:
        items:
          $ref: '#/definitions/models.Article'
        type: array
      page:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
    type: object
host: localhost:8081
info:
  contact: {}
  description: 个人博客系统API文档
  title: Blog API
  version: "1.0"
paths:
  /admin/articles:
    post:
      consumes:
      - application/json
      description: 创建新文章
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文章信息
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/models.Article'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 创建文章
      tags:
      - 文章管理
  /admin/articles/{id}:
    delete:
      consumes:
      - application/json
      description: 软删除文章（设置为不显示）
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 删除文章
      tags:
      - 文章管理
    put:
      consumes:
      - application/json
      description: 更新现有文章
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      - description: 文章信息
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/models.Article'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 更新文章
      tags:
      - 文章管理
  /admin/login:
    post:
      consumes:
      - application/json
      description: 管理员登录并获取JWT令牌
      parameters:
      - description: 登录信息
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/article.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 管理员登录
      tags:
      - 认证
  /articles:
    get:
      consumes:
      - application/json
      description: 获取所有已发布的文章列表，支持分页
      parameters:
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 10
        description: 每页数量
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ArticleListResponse'
      summary: 获取文章列表
      tags:
      - 文章
  /articles/{id}:
    get:
      consumes:
      - application/json
      description: 根据ID获取单篇文章详情
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Article'
      summary: 获取单篇文章
      tags:
      - 文章
swagger: "2.0"
